# Site settings
author: Hunter Sapienza
title: Our Data-Driven World
header-img: img/home-bg.png
email: sapienzahunter@gmail.com
copyright_name: Hunter Sapienza
description: > # this means to ignore newlines until "baseurl:"
  Flatiron School Online Data Science Program Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  huntersapienza

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
